apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ty82
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ty82
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ty82
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ty82
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ty82
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-imdn-tenant/rhtap-demo-app/hacbs-test-project-ty82@sha256:d14745aa34369bbe2dd9a045e81afac3fa0e92f01e2d1e2d99322040468fef56
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
